### ISSUE TITLE
ProcessLasso@12.0.1: hash check failed

### ISSUE THREAD

**Issue by TidesUnderscore** [jonisb/Misc-scoops#5]
App:         jonisb_Misc-scoops/ProcessLasso
URL:         https://dl.bitsum.com/files/processlassosetup64.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    c7f8e41135ddf6d1539139baa2130d2b8007a0c305fac433d14b6dc3a748d77c
Actual:      d8edf43f7d2793d6f0513a741b78b5b57df4f03ee9c56f624d3fa6bd1040e461

**Comment by jonisb** [comment]
Thanks for the report. Cool that someone has use of my bucket.
I'll fix it right after.
